// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yattgeryizsliduybfxn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdHRnZXJ5aXpzbGlkdXliZnhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTY5NzAsImV4cCI6MjA3MDI3Mjk3MH0.2K8MQlx6YaDCeF359PoaAPSf6wzI3Tsqqlgv-sZdDyU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});